cmd_scripts/kconfig/qconf.o := g++ -Wp,-MD,scripts/kconfig/.qconf.o.d -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -std=c++11 -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/arm-linux-gnueabihf/qt5 -c -o scripts/kconfig/qconf.o scripts/kconfig/qconf.cc

source_scripts/kconfig/qconf.o := scripts/kconfig/qconf.cc

deps_scripts/kconfig/qconf.o := \
  /usr/include/stdc-predef.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qglobal.h \
  /usr/include/c++/8/type_traits \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/c++config.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/os_defines.h \
  /usr/include/features.h \
  /usr/include/arm-linux-gnueabihf/sys/cdefs.h \
  /usr/include/arm-linux-gnueabihf/bits/wordsize.h \
  /usr/include/arm-linux-gnueabihf/bits/long-double.h \
  /usr/include/arm-linux-gnueabihf/gnu/stubs.h \
  /usr/include/arm-linux-gnueabihf/gnu/stubs-hard.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/cpu_defines.h \
  /usr/include/c++/8/cstddef \
  /usr/lib/gcc/arm-linux-gnueabihf/8/include/stddef.h \
  /usr/include/c++/8/utility \
  /usr/include/c++/8/bits/stl_relops.h \
  /usr/include/c++/8/bits/stl_pair.h \
  /usr/include/c++/8/bits/move.h \
  /usr/include/c++/8/bits/concept_check.h \
  /usr/include/c++/8/initializer_list \
  /usr/include/assert.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qconfig.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qtcore-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsystemdetection.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qprocessordetection.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcompilerdetection.h \
  /usr/include/c++/8/algorithm \
  /usr/include/c++/8/bits/stl_algobase.h \
  /usr/include/c++/8/bits/functexcept.h \
  /usr/include/c++/8/bits/exception_defines.h \
  /usr/include/c++/8/bits/cpp_type_traits.h \
  /usr/include/c++/8/ext/type_traits.h \
  /usr/include/c++/8/ext/numeric_traits.h \
  /usr/include/c++/8/bits/stl_iterator_base_types.h \
  /usr/include/c++/8/bits/stl_iterator_base_funcs.h \
  /usr/include/c++/8/debug/assertions.h \
  /usr/include/c++/8/bits/stl_iterator.h \
  /usr/include/c++/8/bits/ptr_traits.h \
  /usr/include/c++/8/debug/debug.h \
  /usr/include/c++/8/bits/predefined_ops.h \
  /usr/include/c++/8/bits/stl_algo.h \
  /usr/include/c++/8/cstdlib \
  /usr/include/stdlib.h \
  /usr/include/arm-linux-gnueabihf/bits/libc-header-start.h \
  /usr/include/arm-linux-gnueabihf/bits/waitflags.h \
  /usr/include/arm-linux-gnueabihf/bits/waitstatus.h \
  /usr/include/arm-linux-gnueabihf/bits/floatn.h \
  /usr/include/arm-linux-gnueabihf/bits/floatn-common.h \
  /usr/include/arm-linux-gnueabihf/bits/types/locale_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__locale_t.h \
  /usr/include/arm-linux-gnueabihf/sys/types.h \
  /usr/include/arm-linux-gnueabihf/bits/types.h \
  /usr/include/arm-linux-gnueabihf/bits/typesizes.h \
  /usr/include/arm-linux-gnueabihf/bits/types/clock_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/clockid_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/time_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/timer_t.h \
  /usr/include/arm-linux-gnueabihf/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/arm-linux-gnueabihf/bits/endian.h \
  /usr/include/arm-linux-gnueabihf/bits/byteswap.h \
  /usr/include/arm-linux-gnueabihf/bits/uintn-identity.h \
  /usr/include/arm-linux-gnueabihf/sys/select.h \
  /usr/include/arm-linux-gnueabihf/bits/select.h \
  /usr/include/arm-linux-gnueabihf/bits/types/sigset_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__sigset_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_timeval.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_timespec.h \
  /usr/include/arm-linux-gnueabihf/bits/pthreadtypes.h \
  /usr/include/arm-linux-gnueabihf/bits/thread-shared-types.h \
  /usr/include/arm-linux-gnueabihf/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/arm-linux-gnueabihf/bits/stdlib-bsearch.h \
  /usr/include/arm-linux-gnueabihf/bits/stdlib-float.h \
  /usr/include/c++/8/bits/std_abs.h \
  /usr/include/c++/8/bits/algorithmfwd.h \
  /usr/include/c++/8/bits/stl_heap.h \
  /usr/include/c++/8/bits/stl_tempbuf.h \
  /usr/include/c++/8/bits/stl_construct.h \
  /usr/include/c++/8/new \
  /usr/include/c++/8/exception \
  /usr/include/c++/8/bits/exception.h \
  /usr/include/c++/8/bits/exception_ptr.h \
  /usr/include/c++/8/bits/cxxabi_init_exception.h \
  /usr/include/c++/8/typeinfo \
  /usr/include/c++/8/bits/hash_bytes.h \
  /usr/include/c++/8/bits/nested_exception.h \
  /usr/include/c++/8/ext/alloc_traits.h \
  /usr/include/c++/8/bits/alloc_traits.h \
  /usr/include/c++/8/bits/memoryfwd.h \
  /usr/include/c++/8/bits/uniform_int_dist.h \
  /usr/include/c++/8/limits \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qtypeinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsysinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlogging.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qflags.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qatomic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbasicatomic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qatomic_cxx11.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qgenericatomic.h \
  /usr/include/c++/8/atomic \
  /usr/include/c++/8/bits/atomic_base.h \
  /usr/lib/gcc/arm-linux-gnueabihf/8/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/arm-linux-gnueabihf/bits/wchar.h \
  /usr/include/arm-linux-gnueabihf/bits/stdint-uintn.h \
  /usr/include/c++/8/bits/atomic_lockfree_defines.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qglobalstatic.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qnumeric.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qversiontagging.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMainWindow \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmainwindow.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtwidgetsglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtguiglobal.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtgui-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtwidgets-config.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qwindowdefs.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qnamespace.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobjectdefs_impl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobject.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstring.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qchar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbytearray.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qrefcount.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qarraydata.h \
  /usr/include/string.h \
  /usr/include/strings.h \
  /usr/include/c++/8/stdlib.h \
  /usr/lib/gcc/arm-linux-gnueabihf/8/include/stdarg.h \
  /usr/include/c++/8/string \
  /usr/include/c++/8/bits/stringfwd.h \
  /usr/include/c++/8/bits/char_traits.h \
  /usr/include/c++/8/bits/postypes.h \
  /usr/include/c++/8/cwchar \
  /usr/include/wchar.h \
  /usr/include/arm-linux-gnueabihf/bits/types/wint_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/mbstate_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__mbstate_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__FILE.h \
  /usr/include/arm-linux-gnueabihf/bits/types/FILE.h \
  /usr/include/c++/8/cstdint \
  /usr/include/c++/8/bits/allocator.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/c++allocator.h \
  /usr/include/c++/8/ext/new_allocator.h \
  /usr/include/c++/8/bits/localefwd.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/c++locale.h \
  /usr/include/c++/8/clocale \
  /usr/include/locale.h \
  /usr/include/arm-linux-gnueabihf/bits/locale.h \
  /usr/include/c++/8/iosfwd \
  /usr/include/c++/8/cctype \
  /usr/include/ctype.h \
  /usr/include/c++/8/bits/ostream_insert.h \
  /usr/include/c++/8/bits/cxxabi_forced.h \
  /usr/include/c++/8/bits/stl_function.h \
  /usr/include/c++/8/backward/binders.h \
  /usr/include/c++/8/bits/range_access.h \
  /usr/include/c++/8/bits/basic_string.h \
  /usr/include/c++/8/ext/atomicity.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/gthr.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/gthr-default.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/arm-linux-gnueabihf/bits/sched.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_sched_param.h \
  /usr/include/arm-linux-gnueabihf/bits/cpu-set.h \
  /usr/include/time.h \
  /usr/include/arm-linux-gnueabihf/bits/time.h \
  /usr/include/arm-linux-gnueabihf/bits/timex.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_tm.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_itimerspec.h \
  /usr/include/arm-linux-gnueabihf/bits/setjmp.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/atomic_word.h \
  /usr/include/c++/8/ext/string_conversions.h \
  /usr/include/c++/8/cstdio \
  /usr/include/stdio.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__fpos_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/__fpos64_t.h \
  /usr/include/arm-linux-gnueabihf/bits/types/struct_FILE.h \
  /usr/include/arm-linux-gnueabihf/bits/types/cookie_io_functions_t.h \
  /usr/include/arm-linux-gnueabihf/bits/stdio_lim.h \
  /usr/include/arm-linux-gnueabihf/bits/sys_errlist.h \
  /usr/include/arm-linux-gnueabihf/bits/stdio.h \
  /usr/include/c++/8/cerrno \
  /usr/include/errno.h \
  /usr/include/arm-linux-gnueabihf/bits/errno.h \
  /usr/include/linux/errno.h \
  /usr/include/arm-linux-gnueabihf/asm/errno.h \
  /usr/include/asm-generic/errno.h \
  /usr/include/asm-generic/errno-base.h \
  /usr/include/arm-linux-gnueabihf/bits/types/error_t.h \
  /usr/include/c++/8/bits/functional_hash.h \
  /usr/include/c++/8/bits/basic_string.tcc \
  /usr/include/c++/8/iterator \
  /usr/include/c++/8/ostream \
  /usr/include/c++/8/ios \
  /usr/include/c++/8/bits/ios_base.h \
  /usr/include/c++/8/bits/locale_classes.h \
  /usr/include/c++/8/bits/locale_classes.tcc \
  /usr/include/c++/8/system_error \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/error_constants.h \
  /usr/include/c++/8/stdexcept \
  /usr/include/c++/8/streambuf \
  /usr/include/c++/8/bits/streambuf.tcc \
  /usr/include/c++/8/bits/basic_ios.h \
  /usr/include/c++/8/bits/locale_facets.h \
  /usr/include/c++/8/cwctype \
  /usr/include/wctype.h \
  /usr/include/arm-linux-gnueabihf/bits/wctype-wchar.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/ctype_base.h \
  /usr/include/c++/8/bits/streambuf_iterator.h \
  /usr/include/arm-linux-gnueabihf/c++/8/bits/ctype_inline.h \
  /usr/include/c++/8/bits/locale_facets.tcc \
  /usr/include/c++/8/bits/basic_ios.tcc \
  /usr/include/c++/8/bits/ostream.tcc \
  /usr/include/c++/8/istream \
  /usr/include/c++/8/bits/istream.tcc \
  /usr/include/c++/8/bits/stream_iterator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringliteral.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringalgorithms.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qalgorithms.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qiterator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qhashfunctions.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qpair.h \
  /usr/include/c++/8/numeric \
  /usr/include/c++/8/bits/stl_numeric.h \
  /usr/include/c++/8/list \
  /usr/include/c++/8/bits/stl_list.h \
  /usr/include/c++/8/bits/allocated_ptr.h \
  /usr/include/c++/8/ext/aligned_buffer.h \
  /usr/include/c++/8/bits/list.tcc \
  /usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed/limits.h \
  /usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/arm-linux-gnueabihf/bits/posix1_lim.h \
  /usr/include/arm-linux-gnueabihf/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/arm-linux-gnueabihf/bits/posix2_lim.h \
  /usr/include/arm-linux-gnueabihf/bits/xopen_lim.h \
  /usr/include/arm-linux-gnueabihf/bits/uio_lim.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qbytearraylist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringlist.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qregexp.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qstringmatcher.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qscopedpointer.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmetatype.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvarlengtharray.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcontainerfwd.h \
  /usr/include/c++/8/vector \
  /usr/include/c++/8/bits/stl_uninitialized.h \
  /usr/include/c++/8/bits/stl_vector.h \
  /usr/include/c++/8/bits/stl_bvector.h \
  /usr/include/c++/8/bits/vector.tcc \
  /usr/include/c++/8/map \
  /usr/include/c++/8/bits/stl_tree.h \
  /usr/include/c++/8/bits/stl_map.h \
  /usr/include/c++/8/tuple \
  /usr/include/c++/8/array \
  /usr/include/c++/8/bits/uses_allocator.h \
  /usr/include/c++/8/bits/invoke.h \
  /usr/include/c++/8/bits/stl_multimap.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qobject_impl.h \
  /usr/include/c++/8/chrono \
  /usr/include/c++/8/ratio \
  /usr/include/c++/8/ctime \
  /usr/include/c++/8/bits/parse_numbers.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmargins.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpaintdevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qrect.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsize.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qpoint.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpalette.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qcolor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qrgb.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qrgba64.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qbrush.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvector.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qmatrix.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpolygon.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qregion.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qdatastream.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qiodevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qline.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtransform.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpainterpath.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qimage.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpixelformat.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpixmap.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsharedpointer.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qshareddata.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qhash.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsharedpointer_impl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfont.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfontmetrics.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qfontinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qsizepolicy.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qcursor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qkeysequence.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtabwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qicon.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/QList \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qevent.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcoreevent.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qvariant.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qmap.h \
  /usr/include/c++/8/functional \
  /usr/include/c++/8/bits/refwrap.h \
  /usr/include/c++/8/bits/std_function.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qset.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qurl.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfile.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfiledevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qvector2d.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtouchdevice.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtextbrowser.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtextedit.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractscrollarea.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qframe.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextdocument.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextoption.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextcursor.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qtextformat.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qpen.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QAction \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qaction.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qactiongroup.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qaction.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QFileDialog \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qfiledialog.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qdir.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qfileinfo.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdialog.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QMenu \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenu.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qcoreapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qeventloop.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qguiapplication.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qinputmethod.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qlocale.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdesktopwidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtoolbar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayoutitem.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qboxlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qgridlayout.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qsplitter.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlineedit.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlabel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qpushbutton.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractbutton.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenubar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmenu.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qmessagebox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qregexp.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qevent.h \
  scripts/kconfig/lkc.h \
    $(wildcard include/config/prefix.h) \
  scripts/kconfig/expr.h \
  scripts/kconfig/list.h \
  scripts/kconfig/lkc_proto.h \
  scripts/kconfig/qconf.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QTextBrowser \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtextbrowser.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QTreeWidget \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreewidget.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreeview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractitemview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qabstractitemmodel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qitemselectionmodel.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractitemdelegate.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qstyleoption.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractspinbox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtGui/qvalidator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qregularexpression.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qslider.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qabstractslider.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qstyle.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtabbar.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qrubberband.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qtreewidgetitemiterator.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QHeaderView \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qheaderview.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsettings.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QPushButton \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qpushbutton.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/QSettings \
  /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsettings.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QLineEdit \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qlineedit.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QSplitter \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qsplitter.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QCheckBox \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qcheckbox.h \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/QDialog \
  /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qdialog.h \
  scripts/kconfig/qconf.moc \
  scripts/kconfig/images.h \

scripts/kconfig/qconf.o: $(deps_scripts/kconfig/qconf.o)

$(deps_scripts/kconfig/qconf.o):
